export const DEGREES = Array.from({ length: 33 }, (_, i) => {
  const n = i + 1;
  const suffix =
    n === 1 ? "st" : n === 2 ? "nd" : n === 3 ? "rd" : "th";
  return { value: n, label: `${n}${suffix}` };
});

export const COUNTRIES = [
  "Argentina",
  "Australia",
  "Belgium",
  "Bolivia",
  "Brazil",
  "Canada",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Dominican Republic",
  "Ecuador",
  "El Salvador",
  "England",
  "France",
  "Germany",
  "Greece",
  "Guatemala",
  "Haiti",
  "Honduras",
  "India",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Mexico",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Portugal",
  "Puerto Rico",
  "Scotland",
  "South Africa",
  "Spain",
  "Sweden",
  "Switzerland",
  "Trinidad and Tobago",
  "Turkey",
  "United States",
  "Uruguay",
  "Venezuela",
] as const;
